name: Test

on: [pull_request]

jobs:
  test_alpine:
    name: Ruby ${{ matrix.ruby_version }}
    runs-on: ubuntu-latest
    container: ruby:${{ matrix.ruby_version }}-alpine
    strategy:
      fail-fast: false
      matrix:
        ruby_version: ["2.7", "3.0", "3.1", "3.2"]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          apk add --no-cache build-base git less
          bundle install
      - name: Unit testing
        run: bundle exec rake test
